### ISSUE TITLE
Upgrade to js-interpreter@3.0.1

### ISSUE THREAD

**Issue by aminmarashi** [formio/protected-eval#4]
[js-interpreter](https://www.npmjs.com/package/js-interpreter) has recently been updated with some performance enhancements, upgarding to 3.0.1 would probably increase the speed of form.io significantly, therefore it's worth upgrading.

Opening a PR is simple enough, but I wasn't sure how to test the library, if you want me to, I can open a PR with the required changes.

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
